---
- name: Ensure postgresql is running
  ansible.builtin.service:
    name: postgresql
    state: started

- name: Is postgresql_database set
  ansible.builtin.assert:
    that:
      - postgresql_database != None
    fail_msg: "Set the postgresql_database variable"

- name: Is postgresql_user set
  ansible.builtin.assert:
    that:
      - postgresql_user != None
    fail_msg: "Set the postgresql_user variable"

- name: Create database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ postgresql_database }}"
    encoding: "UTF-8"
    lc_collate: "C.UTF-8"
    lc_ctype: "C.UTF-8"
    owner: "{{ postgresql_user }}"
    template: "template0"
    state: present
