---
- name: Install postgres for Debian systems
  ansible.builtin.import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - postgres
    - postgres.install

- name: Set the state of the service
  ansible.builtin.service:
    name: postgresql
    state: "{{ postgresql_state }}"
  tags:
    - postgres
    - postgres.service
