---
- name: Install postgres for Debian systems
  ansible.builtin.import_tasks: install.yml
  tags:
    - postgres
    - postgres.install

- name: Create role for app
  ansible.builtin.import_tasks: create-role.yml
  tags:
    - postgres
    - postgres.setup

- name: Create database for app
  ansible.builtin.import_tasks: create-database.yml
  tags:
    - postgres
    - postgres.setup

- name: Set the state of the service
  ansible.builtin.service:
    name: postgresql
    state: "{{ postgresql_state }}"
  tags:
    - postgres
    - postgres.service
