---
- name: Generate self-signed certificate
  ansible.builtin.command:
    cmd: >
      openssl req -x509 -nodes -subj '/CN={{ ansible_hostname }}' -days 365
      -newkey rsa:4096 -sha256 -keyout /etc/ssl/private/server.key -out /etc/ssl/private/server.crt
    creates: "/etc/ssl/private/server.crt"
