---
- name: Install Nginx
  ansible.builtin.apt:
    name: "{{ nginx_packages }}"

- name: Set up parameters for Diffie-Hellman Key Exchange
  ansible.builtin.command:
    cmd: openssl dhparam -out /etc/ssl/certs/dhparams.pem 4096
    creates: /etc/ssl/certs/dhparams.pem

- name: Enable/disable the service at boot
  ansible.builtin.service:
    name: nginx
    enabled: "{{ nginx_enabled }}"
