---
- name: Install Nginx
  ansible.builtin.apt:
    name: "{{ nginx_deb_packages }}"

- name: Set up parameters for Diffie-Hellman Key Exchange
  ansible.builtin.command: openssl dhparam -out /etc/ssl/certs/dhparams.pem 2048 creates=/etc/ssl/certs/dhparams.pem
  when: nginx_diffie_hellman_enable is defined and nginx_diffie_hellman_enable

- name: Enable/disable the service at boot
  ansible.builtin.service:
    name: nginx
    enabled: "{{ nginx_enabled }}"
