---
- name: Install nginx for Debian systems
  ansible.builtin.import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - nginx
    - nginx.install

- name: Create SSL certificate - development ONLY
  ansible.builtin.import_tasks: create-certificate.yml
  when: app_domain_name is not defined
  tags:
    - nginx
    - nginx.certificate

- name: Disable default site
  ansible.builtin.import_tasks: disable-default-site.yml
  tags:
    - nginx
    - nginx.setup

- name: Add site for app
  ansible.builtin.import_tasks: add-site.yml
  tags:
    - nginx
    - nginx.setup
  notify:
    - "Reload nginx"

- name: Set the state of the service
  ansible.builtin.service:
    name: nginx
    state: "{{ nginx_state }}"
  tags:
    - nginx
    - nginx.service
