---
- name: Create swap file
  ansible.builtin.command:
    cmd: "{{ swap_command }}"
    creates: "{{ swap_file_path }}"
  register: swap_file_create

- name: Set permissions
  ansible.builtin.file:
    path: "{{ swap_file_path }}"
    owner: root
    group: root
    mode: 0600
  changed_when: false

- name: Format swap file  # noqa no-handler
  ansible.builtin.command: "mkswap {{ swap_file_path }}"
  when: swap_file_create is changed
  changed_when: false

- name: Mount swap
  ansible.posix.mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: "{{ swap_file_opts }}"
    passno: 0
    dump: 0
    state: present

- name: Enable swap  # noqa no-handler
  ansible.builtin.command: "swapon {{ swap_file_path }}"
  when: swap_file_create is changed
  changed_when: false

- name: Set swappiness.
  ansible.posix.sysctl:
    name: vm.swappiness
    value: "{{ swap_swappiness }}"
    state: present
