---
# The set of environment variables needed to specifically configure celery.
celery_environment:
  BROKER_URL: "{{ rabbitmq_uri }}"
  DATABASE_URL: "{{ postgres_uri }}"
  DJANGO_DEBUG: "{{ django_debug }}"
  DJANGO_ENV: "{{ env_name }}"
  DJANGO_MEDIA_ROOT: "{{ app_media_dir }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DJANGO_STATIC_ROOT: "{{ app_static_dir }}"
