---
- name: Install rabbitmq for Debian systems
  ansible.builtin.import_tasks: install.yml
  tags:
    - rabbitmq
    - rabbitmq.install

- name: Remove guest user
  ansible.builtin.import_tasks: remove-guest.yml
  tags:
    - rabbitmq
    - rabbitmq.setup

- name: Create vhost for app
  ansible.builtin.import_tasks: create-vhost.yml
  tags:
    - rabbitmq
    - rabbitmq.setup

- name: Create vhost user
  ansible.builtin.import_tasks: create-user.yml
  tags:
    - rabbitmq
    - rabbitmq.setup

- name: Set the state of the service
  ansible.builtin.service:
    name: rabbitmq-server
    state: "{{ rabbitmq_state }}"
  tags:
    - rabbitmq
    - rabbitmq.service
