---
- name: Install setuptools
  ansible.builtin.pip:
    virtualenv: "{{ python_virtualenv_dir }}"
    name: "setuptools"

- name: Install requirements
  ansible.builtin.pip:
    virtualenv: "{{ python_virtualenv_dir }}"
    requirements: "{{ python_requirements_file }}"
