---
- name: Install unattended upgrades for Debian systems
  ansible.builtin.import_tasks: install.yml
  tags:
    - updates

- name: Set up unattended upgrades for Debian systems
  ansible.builtin.import_tasks: setup.yml
  tags:
    - updates
