---
- name: Restart supervisor
  community.general.supervisorctl:
    name: "{{ app_name }}_django"
    state: restarted
  listen: Restart django

- name: Restart memcached
  ansible.builtin.service:
    name: memcached
    state: restarted
  listen: Restart django
