---
# The path to the settings module
django_settings_module: !!null

# The hosts allowed to connect to the server
django_allowed_hosts: "{{ app_domain_name | default(inventory_hostname) }}"

# The set of environment variables needed to configure Django
django_environment:
  BROKER_URL: "{{ rabbitmq_uri }}"
  DATABASE_URL: "{{ postgres_uri }}"
  DJANGO_ALLOWED_HOSTS: "{{ django_allowed_hosts }}"
  DJANGO_MEDIA_ROOT: "{{ app_media_dir }}"
  DJANGO_SECRET_KEY: "{{ django_secret_key }}"
  DJANGO_STATIC_ROOT: "{{ app_static_dir }}"
