---
- name: Install packages
  ansible.builtin.apt:
    name: "{{ supervisor_packages }}"

- name: Enable/disable the service at boot
  ansible.builtin.service:
    name: supervisor
    enabled: "{{ supervisor_enabled }}"
