---
- name: Install supervisor for Debian systems
  ansible.builtin.import_tasks: install-debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - supervisor
    - supervisor.install

- name: Set the state of the service
  ansible.builtin.service:
    name: supervisor
    state: "{{ supervisor_state }}"
  tags:
    - supervisor
    - supervisor.service
