---
# The absolute path to the swap file
swap_file_path: /swapfile

# The size of the filesystem blocks
swap_file_block_size: "1M"

# The number of blocks to allocate
swap_file_blocks: "1024"

# Mount options in fstab. sw indicates swap space. You can also
# add multiple swap partitions/fixes and prioritise how the swap
# system uses them.
swap_file_opts: "sw"

# Kernel parameter controlling how aggressive swapping is implemented
# 0        The value instructs the kernel to avoid swappiness as much as possible.
# 10-50    The value tells the kernel to be slightly aggressive in swapping out memory pages.
# 50-100   The value instructs the kernel to be moderately aggressive in swapping out memory pages.
# 100-200  The higher values instructs the kernel to be very aggressive in swapping out memory pages.
swap_swappiness: 60

# The command used to initialize the swap file.
swap_command: "dd if=/dev/zero of={{ swap_file_path }} bs={{ swap_file_block_size }} count={{ swap_file_blocks }}"
