---
- name: Generate certificate
  ansible.builtin.command: "/usr/bin/certbot certonly --noninteractive --agree-tos --standalone --email {{ certbot_admin_email }} -d {{ inventory_hostname }}"
  args:
    creates: "/etc/letsencrypt/live/{{ inventory_hostname }}/"
