---
- name: Add users
  ansible.builtin.user:
    name: "{{ item.username }}"
    uid: "{{ item.uid | default(omit, True) }}"
    password: "{{ item.password }}"
    update_password: "on_create"
    shell: "{{ item.shell }}"
    createhome: true
    comment: "{{ item.comment }}"
    state: "{{ item.state }}"
  when: item.group_names | intersect(group_names)
  loop: "{{ admins }}"
  loop_control:
    label: "username: {{ item.username }}, state: {{ item.state }}"

- name: Disable root login
  ansible.builtin.user:
    name: root
    password_lock: true
