---

- name: Is django_settings_module set
  ansible.builtin.assert:
    that:
      - django_settings_module != None
    fail_msg: "Set the django_settings_module variable"
  tags:
    - django
    - django.setup
    - deploy

- name: Delete compiled python files in app
  ansible.builtin.import_tasks: delete-compiled-files.yml
  tags:
    - django
    - django.setup
    - deploy

- name: Generate dotenv
  ansible.builtin.import_tasks: setup-dotenv.yml
  tags:
    - django
    - django.setup
    - deploy

- name: Run database migrations
  ansible.builtin.import_tasks: run-migrations.yml
  tags:
    - django
    - django.setup
    - deploy

- name: Run collectstatic
  ansible.builtin.import_tasks: run-collectstatic.yml
  tags:
    - django
    - django.setup
    - deploy

- name: Notify memcached
  command: /bin/true
  tags:
    - deploy
  notify:
    - "Restart memcached"

- name: Notify supervisor
  command: /bin/true
  tags:
    - deploy
  notify:
    - "Restart supervisor"
