---
- name: Delete compiled python files in app
  ansible.builtin.import_tasks: delete-compiled-files.yml
  tags:
    - django
    - django.setup
    - deploy

- name: Create nginx site
  ansible.builtin.import_tasks: setup-nginx.yml
  tags:
    - django
    - django.nginx

- name: Generate dotenv
  ansible.builtin.import_tasks: setup-dotenv.yml
  tags:
    - django
    - django.setup
    - deploy

- name: Run database migrations
  ansible.builtin.import_tasks: run-migrations.yml
  tags:
    - django
    - django.setup
    - deploy

- name: Run collectstatic
  ansible.builtin.import_tasks: run-collectstatic.yml
  tags:
    - django
    - django.setup
    - deploy
