---
- name: Delete compiled python files in app
  ansible.builtin.import_tasks: delete-compiled-files.yml
  tags:
    - django
    - django.setup
    - deploy

- name: Create nginx site
  ansible.builtin.import_tasks: setup-nginx.yml
  tags:
    - django
    - django.nginx

- name: Setup Django
  ansible.builtin.import_tasks: setup-django.yml
  tags:
    - django
    - django.setup
    - deploy
  notify:
    - "Restart django"
