---
- name: Create rabbitmq vhost
  community.rabbitmq.rabbitmq_vhost:
    name: "{{ broker_vhost }}"
    state: present

- name: Create rabbitmq user
  community.rabbitmq.rabbitmq_user:
    user: "{{ broker_user }}"
    password: "{{ broker_password }}"
    vhost: "{{ broker_vhost }}"
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
