---
- name: Disable default site
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Set up site
  ansible.builtin.template:
    src: nginx_config.j2
    dest: "/etc/nginx/sites-available/{{ app_name }}"
    backup: true
    mode: '0644'
  notify: "Reload nginx"

- name: Enable site
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ app_name }}"
    dest: "/etc/nginx/sites-enabled/{{ app_name }}"
    state: link
