---
- name: Ensure postgresql is running
  ansible.builtin.service:
    name: postgresql
    state: started

- name: Create role
  become: true
  become_user: postgres
  community.postgresql.postgresql_user:
    db: postgres
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    encrypted: true
    state: present

- name: Create database
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    encoding: "UTF-8"
    lc_collate: "C.UTF-8"
    lc_ctype: "C.UTF-8"
    owner: "{{ db_user }}"
    template: "template0"
    state: present
