---
# The unique key used in cryptographic signing
django_secret_key: "{{ vault_django_secret_key }}"

# The list of users who will be granted access to the servers
admins: "{{ vault_admins }}"

# A cron-job is created to automatically renew the certificate
certbot_enabled: true
# Email used for registration and recovery contact.
# Use a comma-separated list for multiple emails
certbot_admin_email: "{{ vault_certbot_admin_email }}"

# Use fail2ban
fail2ban_enabled: true

# The username/password for the account that connects to the postgreSQL database
postgresql_user: "{{ vault_postgresql_user }}"
postgresql_password: "{{ vault_postgresql_password }}"
# The name of the database
postgresql_database: "{{ app_name }}"

# The username/password for the account that connects to message broker
rabbitmq_user: "{{ vault_rabbitmq_user }}"
rabbitmq_password: "{{ vault_rabbitmq_password }}"
# The broker virtual host for the app
rabbitmq_vhost: "{{ app_name }}"
