---
# IMPORTANT: You must set the following variables: app_name, app_repository,
# and app_environment.

# The name of the app
app_name: !!null

# The URI to the repository containing the app source code.
app_repository: !!null

# Add any additional environment variables for Django here.
app_environment: !!null

# Add any other variables you wish to override here, particularly
# the layout of your Django app, if it differs from the default
# layout assumed in roles/app/defaults/main.yml
